services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    image: ware-voice-web
    container_name: web
    ports:
      - "4200:4200"

volumes:
  postgres-data: